from __future__ import annotations

BARBARA_CHARACTER_HANDLER_KEY = "character.barbara"

BARBARA_NORMAL_ATTACK_1_ACTION_KEY = "character.barbara.normal_attack.1"
BARBARA_NORMAL_ATTACK_2_ACTION_KEY = "character.barbara.normal_attack.2"
BARBARA_NORMAL_ATTACK_3_ACTION_KEY = "character.barbara.normal_attack.3"
BARBARA_NORMAL_ATTACK_4_ACTION_KEY = "character.barbara.normal_attack.4"
BARBARA_CHARGED_ATTACK_ACTION_KEY = "character.barbara.charged_attack"
BARBARA_ELEMENTAL_SKILL_ACTION_KEY = "character.barbara.elemental_skill"
BARBARA_ELEMENTAL_BURST_ACTION_KEY = "character.barbara.elemental_burst"
BARBARA_JUMP_ACTION_KEY = "character.barbara.jump"

BARBARA_NORMAL_ATTACK_1_IMPACT_KEY = f"{BARBARA_NORMAL_ATTACK_1_ACTION_KEY}.hit"
BARBARA_NORMAL_ATTACK_2_IMPACT_KEY = f"{BARBARA_NORMAL_ATTACK_2_ACTION_KEY}.hit"
BARBARA_NORMAL_ATTACK_3_IMPACT_KEY = f"{BARBARA_NORMAL_ATTACK_3_ACTION_KEY}.hit"
BARBARA_NORMAL_ATTACK_4_IMPACT_KEY = f"{BARBARA_NORMAL_ATTACK_4_ACTION_KEY}.hit"
BARBARA_CHARGED_ATTACK_IMPACT_KEY = f"{BARBARA_CHARGED_ATTACK_ACTION_KEY}.hit"
BARBARA_ELEMENTAL_SKILL_IMPACT_KEY = f"{BARBARA_ELEMENTAL_SKILL_ACTION_KEY}.hit"
BARBARA_JUMP_IMPACT_KEY = f"{BARBARA_JUMP_ACTION_KEY}.hit"

BARBARA_HIT_IMPACT_KEYS = (
    BARBARA_NORMAL_ATTACK_1_IMPACT_KEY,
    BARBARA_NORMAL_ATTACK_2_IMPACT_KEY,
    BARBARA_NORMAL_ATTACK_3_IMPACT_KEY,
    BARBARA_NORMAL_ATTACK_4_IMPACT_KEY,
    BARBARA_CHARGED_ATTACK_IMPACT_KEY,
    BARBARA_ELEMENTAL_SKILL_IMPACT_KEY,
    BARBARA_JUMP_IMPACT_KEY,
)
