from __future__ import annotations

from enum import Enum, auto


class EventType(Enum):
    """核心事件类型。"""

    SIMULATION_STARTED = auto()
    SIMULATION_ENDED = auto()
    FRAME_STARTED = auto()
    FRAME_ENDED = auto()
    INPUT_KEY_RECEIVED = auto()
    INPUT_SESSION_BOUNDARY_REACHED = auto()
    DAMAGE_RESOLVED = auto()
    HEALING_RESOLVED = auto()
    CHARACTER_HEALTH_CHANGED = auto()
    CHARACTER_MAX_HP_CHANGED = auto()
    SHIELD_GRANTED = auto()
    SHIELD_CAPACITY_CHANGED = auto()
    SHIELD_REMOVED = auto()
    SHIELD_ABSORPTION_RESOLVED = auto()
    DAMAGE_APPLIED = auto()
    BUFF_APPLIED = auto()
    BUFF_REMOVED = auto()
    INFUSION_APPLIED = auto()
    INFUSION_REMOVED = auto()
    ENERGY_PICKUP_SPAWNED = auto()
    ENERGY_PICKUP_SETTLED = auto()
    DIRECT_ENERGY_CHANGE_RESOLVED = auto()
    CHARACTER_ENERGY_CHANGED = auto()
    AURA_ICD_RESOLVED = auto()
    AURA_APPLIED = auto()
    AURA_DEPLETED = auto()
    AURA_INTERACTION_RESOLVED = auto()
    REACTION_STATE_CHANGED = auto()
    REACTION_OCCURRED = auto()
    ELEMENTAL_INTERACTION_RESOLVED = auto()
    MOVEMENT_COLLIDED = auto()
    MOVEMENT_LANDED = auto()
    RESONANCE_ACTIVATED = auto()
    ACTION_STARTED = auto()
    MOONSIGN_LEVEL_SET = auto()
    MOONSIGN_BONUS_APPLIED = auto()
    MOONSIGN_BONUS_EXPIRED = auto()
