"""输入会话、动作解释、动作实例与影响点管理。"""

from genshin_sim.core.actions.actions import (
    TEAM_SWITCH_ACTION_KEY,
    TEAM_SWITCH_TARGET_SLOT_PARAM,
    FallPlungeAction,
    TeamActionInterpreter,
    TeamSwitchAction,
    TimedImpactAction,
)
from genshin_sim.core.actions.enums import (
    ActionDecisionRejectReason,
    ActionInterpretationKind,
    ActionInterpretationTrigger,
    ActionLifecycle,
    ActionLifecycleDirective,
    ActionOwnerKind,
    InputControlState,
    InputPhysicalState,
    InputSessionPolicy,
    SnapshotPolicy,
)
from genshin_sim.core.actions.interpreters import (
    ActionInterpreter,
    ActionInterpreterRegistry,
    ActiveCharacterInterpreterSelector,
    TeamInterpreterSelector,
)
from genshin_sim.core.actions.manager import ActionManager
from genshin_sim.core.actions.models import (
    ActionAdmissionPolicy,
    ActionDecision,
    ActionExecutionContext,
    ActionExecutionRecord,
    ActionExecutionResult,
    ActionImpactPoint,
    ActionInstance,
    ActionInterpretationResult,
    ActionInterruptPolicy,
    ActionOwnerRef,
    CandidateTargetRef,
    ControlActionRequest,
    InputSessionView,
    InterpreterBinding,
    PreparedAction,
    RuntimeInputSession,
    SearchAreaSpec,
    TargetingSpec,
)
from genshin_sim.core.actions.protocols import Action, ActionRegistry

__all__ = [
    "TEAM_SWITCH_ACTION_KEY",
    "TEAM_SWITCH_TARGET_SLOT_PARAM",
    "Action",
    "ActionAdmissionPolicy",
    "ActionDecision",
    "ActionDecisionRejectReason",
    "ActionExecutionContext",
    "ActionExecutionRecord",
    "ActionExecutionResult",
    "ActionImpactPoint",
    "ActionInstance",
    "ActionInterpreter",
    "ActionInterpreterRegistry",
    "ActionInterpretationKind",
    "ActionInterpretationResult",
    "ActionInterpretationTrigger",
    "ActionInterruptPolicy",
    "ActionLifecycle",
    "ActionLifecycleDirective",
    "ActionManager",
    "ActionOwnerKind",
    "ActionOwnerRef",
    "ActionRegistry",
    "ActiveCharacterInterpreterSelector",
    "CandidateTargetRef",
    "ControlActionRequest",
    "FallPlungeAction",
    "InputControlState",
    "InputPhysicalState",
    "InputSessionPolicy",
    "InputSessionView",
    "InterpreterBinding",
    "PreparedAction",
    "RuntimeInputSession",
    "SearchAreaSpec",
    "SnapshotPolicy",
    "TargetingSpec",
    "TeamActionInterpreter",
    "TeamInterpreterSelector",
    "TeamSwitchAction",
    "TimedImpactAction",
]
