"""精确的持久 Aura 状态与批量计划。"""

from genshin_sim.core.systems.aura.enums import (
    AuraApplicationOutcome,
    AuraDecayMode,
    AuraDecayProfilePolicy,
    AuraLossPolicy,
    AuraStrength,
)
from genshin_sim.core.systems.aura.models import (
    AuraApplicationRequest,
    AuraApplicationResult,
    AuraCommitReceipt,
    AuraComponent,
    AuraContribution,
    AuraContributionRef,
    AuraInstanceRef,
    AuraMutationPlan,
    AuraSnapshot,
    AuraStateLinkMutationRequest,
    AuraTargetRecord,
    AuraTransitionResult,
    AuraView,
    BurningAuraApplicationRequest,
    BurningAuraEstablishmentRequest,
    FrozenAuraApplicationRequest,
    QuickenAuraApplicationRequest,
)
from genshin_sim.core.systems.aura.profiles import (
    STANDARD_AURA_PROFILES,
    AuraApplicationProfile,
    AuraApplicationProfileRegistry,
    AuraDecayProfile,
    quicken_decay_profile,
    regular_application_decay_profile,
    regular_application_duration,
)
from genshin_sim.core.systems.aura.runtime import (
    AuraBatchPlanner,
    AuraEventPublicationError,
    AuraRuntime,
    AuraStoreConflictError,
    UnsupportedAuraCombinationError,
)

__all__ = [
    "AuraApplicationOutcome",
    "AuraApplicationProfile",
    "AuraApplicationProfileRegistry",
    "AuraApplicationRequest",
    "AuraApplicationResult",
    "AuraStateLinkMutationRequest",
    "AuraBatchPlanner",
    "AuraCommitReceipt",
    "AuraComponent",
    "AuraContribution",
    "AuraContributionRef",
    "BurningAuraApplicationRequest",
    "BurningAuraEstablishmentRequest",
    "AuraDecayMode",
    "AuraDecayProfile",
    "AuraDecayProfilePolicy",
    "AuraEventPublicationError",
    "AuraInstanceRef",
    "AuraLossPolicy",
    "AuraMutationPlan",
    "AuraRuntime",
    "AuraSnapshot",
    "AuraStoreConflictError",
    "AuraStrength",
    "AuraTargetRecord",
    "AuraTransitionResult",
    "AuraView",
    "FrozenAuraApplicationRequest",
    "QuickenAuraApplicationRequest",
    "STANDARD_AURA_PROFILES",
    "UnsupportedAuraCombinationError",
    "regular_application_decay_profile",
    "regular_application_duration",
    "quicken_decay_profile",
]
