/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets/{asset_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_v1_assets__asset_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_type}/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_v1_assets__asset_type___source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inputs/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Inputs */
        post: operations["validate_inputs_api_v1_inputs_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Results */
        get: operations["list_results_api_v1_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Detail */
        get: operations["get_run_detail_api_v1_results__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{session_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Metrics */
        get: operations["get_run_metrics_api_v1_results__session_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Events */
        get: operations["get_run_events_api_v1_results__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Run */
        post: operations["submit_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["list_workflows_api_v1_workflows_get"];
        put?: never;
        /** Create Workflow */
        post: operations["create_workflow_api_v1_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["get_workflow_api_v1_workflows__workflow_id__get"];
        /** Save Workflow */
        put: operations["save_workflow_api_v1_workflows__workflow_id__put"];
        post?: never;
        /** Delete Workflow */
        delete: operations["delete_workflow_api_v1_workflows__workflow_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_v1_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetListResponse
         * @description 按类型搜索/列表响应。
         */
        AssetListResponse: {
            /** Items */
            items?: components["schemas"]["AssetResponse"][];
        };
        /**
         * AssetResponse
         * @description 资产列表项/详情；不返回 handler_key 或内部 payload。
         */
        AssetResponse: {
            /** Asset Key */
            asset_key: string;
            /** Source Id */
            source_id: string;
            /** Name */
            name: string;
            /** Usable */
            usable: boolean;
            /** Status */
            status?: string | null;
            /** Rarity */
            rarity?: number | null;
            /** Element */
            element?: string | null;
            /** Weapon Type */
            weapon_type?: string | null;
        };
        /**
         * BatchMemberState
         * @description 批次成员对外展示的状态。
         * @enum {string}
         */
        BatchMemberState: "queued" | "running" | "stopping" | "completed" | "failed" | "cancelled";
        /**
         * BatchRunState
         * @description 由成员状态派生的批次状态。
         * @enum {string}
         */
        BatchRunState: "queued" | "running" | "stopping" | "completed" | "partial" | "failed" | "cancelled";
        /**
         * Diagnostic
         * @description 面向输入的诊断项；item_id/path 可空。
         */
        Diagnostic: {
            /**
             * Severity
             * @default error
             */
            severity: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Item Id */
            item_id?: string | null;
            /** Path */
            path?: string | null;
        };
        /**
         * EventItem
         * @description 单条事件。
         */
        EventItem: {
            /** Frame */
            frame: number;
            /** Event Type */
            event_type: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /**
         * EventPageResponse
         * @description 事件分页响应。
         */
        EventPageResponse: {
            /** Items */
            items: components["schemas"]["EventItem"][];
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InputMemberRequest
         * @description 一个已展开成员：稳定 item_id + 完整 SimulationInput 文档。
         */
        InputMemberRequest: {
            /** Item Id */
            item_id: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
        };
        /**
         * MemberValidationResponse
         * @description 单个成员的校验结果。
         */
        MemberValidationResponse: {
            /** Item Id */
            item_id: string;
            /** Ok */
            ok: boolean;
            /** Details */
            details?: components["schemas"]["Diagnostic"][];
        };
        /**
         * MetricValue
         * @description 单个指标数值与口径说明。
         */
        MetricValue: {
            /** Key */
            key: string;
            /** Value */
            value: number;
            /** Definition */
            definition: string;
        };
        /**
         * MetricsResponse
         * @description 摘要指标响应，与 DamageMetrics.to_dict() 一致。
         */
        MetricsResponse: {
            /** Frames Run */
            frames_run: number;
            /** Frames Per Second */
            frames_per_second: number;
            total_damage: components["schemas"]["MetricValue"];
            dps: components["schemas"]["MetricValue"];
            highest_hit: components["schemas"]["MetricValue"];
            average_hit: components["schemas"]["MetricValue"];
            /** Damage Share By Source */
            damage_share_by_source: components["schemas"]["ShareValue"][];
            /** Damage Share By Kind */
            damage_share_by_kind: components["schemas"]["ShareValue"][];
            total_healing: components["schemas"]["MetricValue"];
            /** Healing Share By Source */
            healing_share_by_source: components["schemas"]["ShareValue"][];
        };
        /**
         * RunDetailResponse
         * @description 运行详情（不含事件流、初始快照与完整输入文档）。
         */
        RunDetailResponse: {
            /** Session Id */
            session_id: string;
            /** State */
            state: string;
            /** Name */
            name: string;
            summary: components["schemas"]["RunSummary"] | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Event Count */
            event_count: number;
        };
        /**
         * RunListItem
         * @description 历史运行列表项。
         */
        RunListItem: {
            /** Session Id */
            session_id: string;
            /** State */
            state: string;
            /** Name */
            name: string;
            /** Stop Reason */
            stop_reason: string;
            /** End Frame */
            end_frame: number;
            /** Frames Run */
            frames_run: number;
            /** Created At */
            created_at: string;
            /** Event Count */
            event_count: number;
        };
        /**
         * RunListResponse
         * @description 历史运行列表。
         */
        RunListResponse: {
            /** Items */
            items: components["schemas"]["RunListItem"][];
        };
        /**
         * RunMemberStatus
         * @description 批次状态视图中的成员记录。
         */
        RunMemberStatus: {
            /** Item Id */
            item_id: string;
            state: components["schemas"]["BatchMemberState"];
            /** Session Id */
            session_id?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * RunStatusResponse
         * @description 批次状态视图；成员顺序与提交顺序一致。
         */
        RunStatusResponse: {
            /** Run Id */
            run_id: string;
            /** Name */
            name: string;
            state: components["schemas"]["BatchRunState"];
            /** Concurrency */
            concurrency: number;
            /** Cancel Requested */
            cancel_requested: boolean;
            /** Member Count */
            member_count: number;
            /** Members */
            members: components["schemas"]["RunMemberStatus"][];
        };
        /**
         * RunSummary
         * @description 运行摘要。
         */
        RunSummary: {
            /** Stop Reason */
            stop_reason: string;
            /** End Frame */
            end_frame: number;
            /** Frames Run */
            frames_run: number;
        };
        /**
         * ShareValue
         * @description 按分组统计的占比指标。
         */
        ShareValue: {
            /** Group */
            group: string;
            /** Value */
            value: number;
            /** Definition */
            definition: string;
        };
        /**
         * SubmitRunRequest
         * @description POST /api/v1/runs 请求体。
         */
        SubmitRunRequest: {
            /**
             * Name
             * @default
             */
            name: string;
            /** Concurrency */
            concurrency?: number | null;
            /** Members */
            members: components["schemas"]["InputMemberRequest"][];
        };
        /**
         * ValidateInputsRequest
         * @description POST /api/v1/inputs/validate 请求体。
         */
        ValidateInputsRequest: {
            /** Members */
            members: components["schemas"]["InputMemberRequest"][];
        };
        /**
         * ValidateInputsResponse
         * @description 输入校验响应；顶层 ok 为全部成员通过。
         */
        ValidateInputsResponse: {
            /** Ok */
            ok: boolean;
            /** Members */
            members: components["schemas"]["MemberValidationResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkflowCreateRequest
         * @description 创建工作流请求；name 缺省时使用默认名称。
         */
        WorkflowCreateRequest: {
            /** Name */
            name?: string | null;
        };
        /**
         * WorkflowListItem
         * @description 工作流列表项，不携带完整定义。
         */
        WorkflowListItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * WorkflowListResponse
         * @description 工作流存档列表。
         */
        WorkflowListResponse: {
            /** Items */
            items: components["schemas"]["WorkflowListItem"][];
        };
        /**
         * WorkflowResponse
         * @description 工作流创建/读取/保存响应。
         */
        WorkflowResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Updated At */
            updated_at: string;
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
        };
        /**
         * WorkspaceResponse
         * @description GET /api/v1/workspace 的响应模型。
         */
        WorkspaceResponse: {
            /** Initialized */
            initialized: boolean;
            /** Asset Db Version */
            asset_db_version: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_assets_api_v1_assets__asset_type__get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                asset_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_api_v1_assets__asset_type___source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_type: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_inputs_api_v1_inputs_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateInputsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateInputsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_results_api_v1_results_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_api_v1_results__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_metrics_api_v1_results__session_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_api_v1_results__session_id__events_get: {
        parameters: {
            query?: {
                frame_min?: number | null;
                frame_max?: number | null;
                event_type?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflows_api_v1_workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListResponse"];
                };
            };
        };
    };
    create_workflow_api_v1_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WorkflowCreateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_api_v1_workflows__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_workflow_api_v1_workflows__workflow_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workflow_api_v1_workflows__workflow_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
        };
    };
}
