"""generic 通用构成部件与共享框架。

generic 部件不带键；由内容包包装时传入内容级键与参数。
"""

from genshin_sim.content.generic.constellations import (
    ConstellationMountError,
    DuplicateEffectKeyError,
    mount_effects,
    resolve_effect_specs,
    resolve_unlocked_constellations,
)
from genshin_sim.content.generic.normal_attack import (
    CHAIN_STATE_LAST_ACTION_KEY,
    CHAIN_STATE_LAST_START_FRAME,
    ChainActionInterpreter,
    ChainInterpreterError,
    ChainOwnerRefBuilder,
    ChainSegmentSelector,
    ChainSegmentSpec,
    ChainSpecError,
    ChainSpecValidationError,
    NormalAttackChainSpec,
    build_chain_actions,
    chain_state_schema,
)
from genshin_sim.content.generic.predicates import (
    InvalidPredicateParameterError,
    Predicate,
    PredicateContext,
    PredicateError,
    all_of,
    any_of,
    field_equals,
    has_buff,
    hp_ratio_above,
    hp_ratio_below,
    is_active_character,
    negate,
    stacks_above,
    stacks_at_least,
)
from genshin_sim.content.generic.talents import (
    CompiledScaling,
    CompiledScalingComponent,
    ScalingCompileError,
    ScalingCompiler,
    TalentFrameworkError,
    TalentLevelResolution,
    TalentLevelResolver,
    TalentValidationError,
)

__all__ = [
    "CHAIN_STATE_LAST_ACTION_KEY",
    "CHAIN_STATE_LAST_START_FRAME",
    "ChainActionInterpreter",
    "ChainInterpreterError",
    "ChainOwnerRefBuilder",
    "ChainSegmentSelector",
    "ChainSegmentSpec",
    "ChainSpecError",
    "ChainSpecValidationError",
    "CompiledScaling",
    "CompiledScalingComponent",
    "ConstellationMountError",
    "DuplicateEffectKeyError",
    "InvalidPredicateParameterError",
    "NormalAttackChainSpec",
    "Predicate",
    "PredicateContext",
    "PredicateError",
    "ScalingCompileError",
    "ScalingCompiler",
    "TalentFrameworkError",
    "TalentLevelResolution",
    "TalentLevelResolver",
    "TalentValidationError",
    "all_of",
    "any_of",
    "build_chain_actions",
    "chain_state_schema",
    "field_equals",
    "has_buff",
    "hp_ratio_above",
    "hp_ratio_below",
    "is_active_character",
    "mount_effects",
    "negate",
    "resolve_effect_specs",
    "resolve_unlocked_constellations",
    "stacks_above",
    "stacks_at_least",
]
