"""队伍级规则的具体内容定义。"""

from genshin_sim.content.team.moonsign import (
    MOONSIGN_BONUS_CAP,
    MOONSIGN_BONUS_DURATION_FRAMES,
    MOONSIGN_SCALING_BY_ELEMENT,
)
from genshin_sim.content.team.resonance import (
    DENDRO_EM_20_TRIGGER_KEYS,
    DENDRO_EM_30_TRIGGER_KEYS,
    ELECTRO_PARTICLE_TRIGGER_KEYS,
    RESONANCE_ANEMO,
    RESONANCE_CRYO,
    RESONANCE_DENDRO,
    RESONANCE_DENDRO_EM_20_BUFF_KEY,
    RESONANCE_DENDRO_EM_30_BUFF_KEY,
    RESONANCE_ELECTRO,
    RESONANCE_GEO,
    RESONANCE_GEO_RES_SHRED_BUFF_KEY,
    RESONANCE_HYDRO,
    RESONANCE_INTERWOVEN,
    RESONANCE_KEYS,
    RESONANCE_PYRO,
    create_resonance_buff_definitions,
    create_resonance_definitions,
)

__all__ = [
    "RESONANCE_ANEMO",
    "DENDRO_EM_20_TRIGGER_KEYS",
    "DENDRO_EM_30_TRIGGER_KEYS",
    "ELECTRO_PARTICLE_TRIGGER_KEYS",
    "RESONANCE_CRYO",
    "RESONANCE_DENDRO",
    "RESONANCE_ELECTRO",
    "RESONANCE_GEO",
    "RESONANCE_HYDRO",
    "RESONANCE_INTERWOVEN",
    "RESONANCE_KEYS",
    "RESONANCE_PYRO",
    "RESONANCE_DENDRO_EM_20_BUFF_KEY",
    "RESONANCE_DENDRO_EM_30_BUFF_KEY",
    "RESONANCE_GEO_RES_SHRED_BUFF_KEY",
    "create_resonance_buff_definitions",
    "create_resonance_definitions",
    "MOONSIGN_BONUS_CAP",
    "MOONSIGN_BONUS_DURATION_FRAMES",
    "MOONSIGN_SCALING_BY_ELEMENT",
]
