"""角色队伍护盾的完整聚合、类型化授予和并行吸收入口。"""

from genshin_sim.core.systems.shield.enums import (
    ShieldChangeReason,
    ShieldElement,
    ShieldGrantOutcome,
    ShieldGrantPolicy,
    ShieldLifecycleState,
    ShieldProtectionKind,
    ShieldRemovalReason,
)
from genshin_sim.core.systems.shield.errors import (
    ShieldAtomicCommitError,
    ShieldAttributeError,
    ShieldCapacityError,
    ShieldErrorDetail,
    ShieldInstanceNotFoundError,
    ShieldPlanConflictError,
    ShieldPolicyError,
    ShieldProtectionNotFoundError,
    ShieldStateConflictError,
    ShieldSystemError,
    ShieldTargetMismatchError,
    ShieldValidationError,
)
from genshin_sim.core.systems.shield.formulas import (
    ShieldCapacityComponentResult,
    ShieldCapacityFormula,
    ShieldCapacityFormulaResult,
    ShieldNativeMultiplierResult,
    ShieldNativeMultiplierTerm,
    ShieldScalingTerm,
    normalize_shield_zero,
    validate_non_negative_shield_float,
    validate_shield_float,
)
from genshin_sim.core.systems.shield.handler import (
    ShieldGrantRecord,
    ShieldImpactRequestHandler,
)
from genshin_sim.core.systems.shield.models import (
    ShieldAbsorptionPlan,
    ShieldAbsorptionRequest,
    ShieldAbsorptionResult,
    ShieldCapacityChangeResult,
    ShieldCommitReceipt,
    ShieldGrantCommitReceipt,
    ShieldGrantPlan,
    ShieldGrantRequest,
    ShieldGrantResolution,
    ShieldGrantResult,
    ShieldHitResult,
    ShieldInstanceRef,
    ShieldMutationPlan,
    ShieldProtectionRef,
    ShieldRecord,
    ShieldRemovalResult,
    ShieldState,
)
from genshin_sim.core.systems.shield.resolver import ShieldResolver
from genshin_sim.core.systems.shield.runtime import (
    ShieldRuntime,
    elemental_absorption_multiplier,
)
from genshin_sim.core.systems.shield.snapshots import (
    ShieldInstanceSnapshot,
    ShieldSnapshot,
)
from genshin_sim.core.systems.shield.store import ShieldStore

__all__ = [
    "ShieldAbsorptionPlan",
    "ShieldAbsorptionRequest",
    "ShieldAbsorptionResult",
    "ShieldAtomicCommitError",
    "ShieldAttributeError",
    "ShieldCapacityChangeResult",
    "ShieldCapacityComponentResult",
    "ShieldCapacityError",
    "ShieldCapacityFormula",
    "ShieldCapacityFormulaResult",
    "ShieldChangeReason",
    "ShieldCommitReceipt",
    "ShieldElement",
    "ShieldErrorDetail",
    "ShieldGrantOutcome",
    "ShieldGrantCommitReceipt",
    "ShieldGrantPlan",
    "ShieldGrantPolicy",
    "ShieldGrantRecord",
    "ShieldGrantRequest",
    "ShieldGrantResolution",
    "ShieldGrantResult",
    "ShieldHitResult",
    "ShieldImpactRequestHandler",
    "ShieldInstanceRef",
    "ShieldMutationPlan",
    "ShieldInstanceNotFoundError",
    "ShieldInstanceSnapshot",
    "ShieldNativeMultiplierResult",
    "ShieldNativeMultiplierTerm",
    "ShieldLifecycleState",
    "ShieldPolicyError",
    "ShieldPlanConflictError",
    "ShieldProtectionKind",
    "ShieldProtectionNotFoundError",
    "ShieldProtectionRef",
    "ShieldRemovalReason",
    "ShieldRemovalResult",
    "ShieldRecord",
    "ShieldResolver",
    "ShieldRuntime",
    "ShieldScalingTerm",
    "ShieldSnapshot",
    "ShieldStateConflictError",
    "ShieldState",
    "ShieldStore",
    "ShieldSystemError",
    "ShieldTargetMismatchError",
    "ShieldValidationError",
    "elemental_absorption_multiplier",
    "normalize_shield_zero",
    "validate_non_negative_shield_float",
    "validate_shield_float",
]
