"""generic 通用构成部件与共享框架。

generic 部件不带键；由内容包包装时传入内容级键与参数。
"""

from genshin_sim.content.generic.chain_state import (
    CHAIN_STATE_LAST_ACTION_KEY,
    CHAIN_STATE_LAST_START_FRAME,
    chain_state_schema,
)
from genshin_sim.content.generic.constellations import (
    ConstellationMountError,
    DuplicateEffectKeyError,
    mount_effects,
    resolve_effect_specs,
    resolve_unlocked_constellations,
)
from genshin_sim.content.generic.favonius_windfall import (
    WINDFALL_PARTICLE_COUNT,
    WINDFALL_PICKUP_ELEMENT,
    WINDFALL_PICKUP_KIND,
    WINDFALL_TRAVEL_FRAMES_MAX,
    WINDFALL_TRAVEL_FRAMES_MIN,
    FavoniusWindfallError,
    FavoniusWindfallHook,
    windfall_parameters,
)
from genshin_sim.content.generic.plunge import (
    PLUNGE_ATTACK_DATA_BY_WEAPON_TYPE,
    PLUNGE_HIGH_AIR_HEIGHT,
    PLUNGE_LOW_AIR_HEIGHT,
    PlungeCollisionData,
    PlungeLandingData,
    PlungeWeaponAttackData,
)
from genshin_sim.content.generic.predicates import (
    InvalidPredicateParameterError,
    Predicate,
    PredicateContext,
    PredicateError,
    all_of,
    any_of,
    field_equals,
    has_buff,
    hp_ratio_above,
    hp_ratio_below,
    is_active_character,
    negate,
    stacks_above,
    stacks_at_least,
)
from genshin_sim.content.generic.talents import (
    CompiledScaling,
    CompiledScalingComponent,
    ScalingCompileError,
    ScalingCompiler,
    TalentFrameworkError,
    TalentLevelResolution,
    TalentLevelResolver,
    TalentValidationError,
)
from genshin_sim.content.generic.timed_action import (
    TimedActionSpec,
    TimedActionSpecError,
    TimedActionSpecValidationError,
    build_timed_actions,
)
from genshin_sim.content.generic.transitions import (
    TransitionVerdict,
    TransitionVerdictKind,
    evaluate_transition,
)

__all__ = [
    "CHAIN_STATE_LAST_ACTION_KEY",
    "CHAIN_STATE_LAST_START_FRAME",
    "CompiledScaling",
    "CompiledScalingComponent",
    "ConstellationMountError",
    "DuplicateEffectKeyError",
    "FavoniusWindfallError",
    "FavoniusWindfallHook",
    "InvalidPredicateParameterError",
    "Predicate",
    "PredicateContext",
    "PredicateError",
    "PLUNGE_ATTACK_DATA_BY_WEAPON_TYPE",
    "PLUNGE_HIGH_AIR_HEIGHT",
    "PLUNGE_LOW_AIR_HEIGHT",
    "PlungeCollisionData",
    "PlungeLandingData",
    "PlungeWeaponAttackData",
    "ScalingCompileError",
    "ScalingCompiler",
    "TalentFrameworkError",
    "TalentLevelResolution",
    "TalentLevelResolver",
    "TalentValidationError",
    "TimedActionSpec",
    "TimedActionSpecError",
    "TimedActionSpecValidationError",
    "TransitionVerdict",
    "TransitionVerdictKind",
    "WINDFALL_PARTICLE_COUNT",
    "WINDFALL_PICKUP_ELEMENT",
    "WINDFALL_PICKUP_KIND",
    "WINDFALL_TRAVEL_FRAMES_MAX",
    "WINDFALL_TRAVEL_FRAMES_MIN",
    "all_of",
    "any_of",
    "build_timed_actions",
    "chain_state_schema",
    "evaluate_transition",
    "field_equals",
    "has_buff",
    "hp_ratio_above",
    "hp_ratio_below",
    "is_active_character",
    "mount_effects",
    "negate",
    "resolve_effect_specs",
    "resolve_unlocked_constellations",
    "stacks_above",
    "stacks_at_least",
    "windfall_parameters",
]
