"""仿真配置契约和校验。"""

from genshin_sim.application.config.errors import ConfigError, ConfigFileError
from genshin_sim.application.config.models import (
    SIMULATION_CONFIG_KIND,
    SUPPORTED_SCHEMA_VERSION,
    ArtifactConfig,
    ArtifactSetConfig,
    CharacterConfig,
    InputFrameConfig,
    KeyEventConfig,
    RuleConfig,
    RunOptions,
    SceneConfig,
    ScenePlayerConfig,
    SceneTargetConfig,
    SimulationConfig,
    SimulationMeta,
    TeamSlotConfig,
    Vector3Config,
    WeaponConfig,
    load_simulation_config,
)

__all__ = [
    "ArtifactConfig",
    "ArtifactSetConfig",
    "CharacterConfig",
    "ConfigError",
    "ConfigFileError",
    "InputFrameConfig",
    "KeyEventConfig",
    "RuleConfig",
    "RunOptions",
    "SceneConfig",
    "ScenePlayerConfig",
    "SceneTargetConfig",
    "SIMULATION_CONFIG_KIND",
    "SUPPORTED_SCHEMA_VERSION",
    "SimulationConfig",
    "SimulationMeta",
    "TeamSlotConfig",
    "Vector3Config",
    "WeaponConfig",
    "load_simulation_config",
]
