"""元素状态帧与元素交互协调器。"""

from genshin_sim.core.coordination.elemental_reaction.bloom import (
    BloomCoreTriggerCoordinator,
    BloomCoreTriggerError,
    BloomCoreTriggerRequest,
    BloomCoreTriggerResult,
    SprawlingShotResolutionRequest,
    SprawlingShotResolutionResult,
)
from genshin_sim.core.coordination.elemental_reaction.capabilities import (
    REACTION_CAPABILITY_PREFIX,
    ReactionCapabilityEvidence,
    ReactionEligibilityView,
    validate_reaction_capability_key,
)
from genshin_sim.core.coordination.elemental_reaction.eligibility import (
    DefaultReactionTargetEligibilityPort,
)
from genshin_sim.core.coordination.elemental_reaction.errors import (
    ElementalInteractionError,
)
from genshin_sim.core.coordination.elemental_reaction.interaction import (
    ElementalInteractionCoordinator,
)
from genshin_sim.core.coordination.elemental_reaction.lifecycle import (
    CrystallizeShardAlreadyPickedError,
    CrystallizeShardExpiredError,
    CrystallizeShardNotFoundError,
    CrystallizeShardOperationConflictError,
    CrystallizeShardPickupCoordinator,
    CrystallizeShardPickupRequest,
    CrystallizeShardPickupResult,
    DendroCoreExpiryCoordinator,
    DendroCoreExpiryResult,
    LunarCageExpiryCoordinator,
    LunarStormCloudExpiryCoordinator,
    ReactionBoundEntityExpiryCoordinator,
    ReactionBoundEntityLifecycleError,
)
from genshin_sim.core.coordination.elemental_reaction.links import (
    BurningStateLinkBatchCoordinator,
    BurningStateLinkConflictError,
    ElementalStateLinkBatchCoordinator,
    ElementalStateLinkConflictError,
    FrozenStateLinkBatchCoordinator,
    FrozenStateLinkBatchReceipt,
    QuickenStateLinkBatchCoordinator,
    QuickenStateLinkConflictError,
    validate_burning_state_links,
    validate_elemental_state_links,
    validate_frozen_state_links,
)
from genshin_sim.core.coordination.elemental_reaction.models import (
    CommittedElementalImpactEvidence,
    DamageImpactWork,
    ElementalInteractionBatchKind,
    ElementalInteractionBatchRecord,
    ElementalSettlementWork,
    ElementalSettlementWorkKind,
    ReactionDecisionStepRecord,
    ReactionTargetCapability,
    ReactionTargetEffectOutcome,
    ReactionTargetEligibility,
    ReactionTargetRelation,
    SimultaneousElementApplicationBatch,
    SimultaneousElementApplicationPolicy,
    SimultaneousElementApplicationPolicyError,
    SimultaneousElementApplicationPolicyRegistry,
    SimultaneousElementApplicationPolicyResult,
    SimultaneousElementApplicationStrategy,
)
from genshin_sim.core.coordination.elemental_reaction.observers import (
    CharacterCrystallizeSourceObserver,
    CharacterTransformativeSourceObserver,
)
from genshin_sim.core.coordination.elemental_reaction.protocols import (
    CrystallizeSourceObservationPort,
    FreezeResistanceObservationPort,
    ReactionEligibilityReadPort,
    ReactionGeneratedImpactDamageInputAdapter,
    ReactionSpatialPlanningPort,
)
from genshin_sim.core.coordination.elemental_reaction.settlement import (
    ElementalSettlementQueueError,
    ElementalSettlementRoundLimitError,
    ElementalSettlementWorkQueue,
)
from genshin_sim.core.coordination.elemental_reaction.settlement_coordinator import (
    ElementalSettlementCoordinator,
)
from genshin_sim.core.coordination.elemental_reaction.simultaneous import (
    NoAuraElectroHydroCoexistencePolicy,
)
from genshin_sim.core.coordination.elemental_reaction.spatial import (
    ReactionSpatialPlanningAdapter,
    ReactionStateBindingConflictError,
    validate_reaction_state_space_bindings,
    validate_reaction_state_space_terminalizations,
)
from genshin_sim.core.coordination.elemental_reaction.state_frame import (
    ElementalStateFrameCoordinator,
    ElementalStateFrameRecord,
)
from genshin_sim.core.coordination.elemental_reaction.state_planning import (
    BurningStateEstablishmentAdapter,
    BurningStateMaintenanceAdapter,
    BurningStateTerminationAdapter,
    QuickenStateCoverageAdapter,
    QuickenStateEstablishmentAdapter,
    QuickenStateTerminationAdapter,
    ReactionStatePlanningAdapterRegistry,
    create_default_state_planning_adapter_registry,
)
from genshin_sim.core.coordination.elemental_reaction.status import (
    ReactionStatusBuffAdapter,
    superconduct_buff_definition,
)

__all__ = [
    "DamageImpactWork",
    "REACTION_CAPABILITY_PREFIX",
    "ReactionCapabilityEvidence",
    "ReactionEligibilityReadPort",
    "ReactionEligibilityView",
    "CommittedElementalImpactEvidence",
    "BloomCoreTriggerCoordinator",
    "BloomCoreTriggerError",
    "BloomCoreTriggerRequest",
    "BloomCoreTriggerResult",
    "DefaultReactionTargetEligibilityPort",
    "CharacterCrystallizeSourceObserver",
    "CharacterTransformativeSourceObserver",
    "CrystallizeSourceObservationPort",
    "CrystallizeShardAlreadyPickedError",
    "CrystallizeShardExpiredError",
    "CrystallizeShardNotFoundError",
    "CrystallizeShardOperationConflictError",
    "CrystallizeShardPickupCoordinator",
    "CrystallizeShardPickupRequest",
    "CrystallizeShardPickupResult",
    "DendroCoreExpiryCoordinator",
    "DendroCoreExpiryResult",
    "LunarCageExpiryCoordinator",
    "LunarStormCloudExpiryCoordinator",
    "ElementalInteractionBatchKind",
    "ElementalInteractionBatchRecord",
    "ElementalInteractionCoordinator",
    "ElementalInteractionError",
    "ElementalSettlementQueueError",
    "ElementalSettlementRoundLimitError",
    "ElementalStateLinkConflictError",
    "ElementalStateLinkBatchCoordinator",
    "BurningStateLinkBatchCoordinator",
    "BurningStateLinkConflictError",
    "BurningStateEstablishmentAdapter",
    "BurningStateMaintenanceAdapter",
    "BurningStateTerminationAdapter",
    "QuickenStateCoverageAdapter",
    "QuickenStateEstablishmentAdapter",
    "QuickenStateTerminationAdapter",
    "create_default_state_planning_adapter_registry",
    "FrozenStateLinkBatchCoordinator",
    "FrozenStateLinkBatchReceipt",
    "QuickenStateLinkBatchCoordinator",
    "QuickenStateLinkConflictError",
    "FreezeResistanceObservationPort",
    "ElementalSettlementCoordinator",
    "ElementalSettlementWork",
    "ElementalSettlementWorkKind",
    "ElementalSettlementWorkQueue",
    "ElementalStateFrameCoordinator",
    "ElementalStateFrameRecord",
    "NoAuraElectroHydroCoexistencePolicy",
    "ReactionStatusBuffAdapter",
    "ReactionStatePlanningAdapterRegistry",
    "ReactionTargetCapability",
    "ReactionDecisionStepRecord",
    "ReactionGeneratedImpactDamageInputAdapter",
    "ReactionSpatialPlanningAdapter",
    "ReactionSpatialPlanningPort",
    "validate_reaction_capability_key",
    "ReactionBoundEntityExpiryCoordinator",
    "ReactionBoundEntityLifecycleError",
    "ReactionStateBindingConflictError",
    "ReactionTargetEffectOutcome",
    "ReactionTargetEligibility",
    "ReactionTargetRelation",
    "SimultaneousElementApplicationBatch",
    "SimultaneousElementApplicationPolicy",
    "SimultaneousElementApplicationPolicyError",
    "SimultaneousElementApplicationPolicyRegistry",
    "SimultaneousElementApplicationPolicyResult",
    "SimultaneousElementApplicationStrategy",
    "SprawlingShotResolutionRequest",
    "SprawlingShotResolutionResult",
    "superconduct_buff_definition",
    "validate_frozen_state_links",
    "validate_burning_state_links",
    "validate_elemental_state_links",
    "validate_reaction_state_space_bindings",
    "validate_reaction_state_space_terminalizations",
]
